name: Godot 4 Migration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Godot 4.3 Headless
      - name: Set up Godot 4.3
        uses: firebelley/godot-export@v1
        with:
          godot-version: "4.3.0"
          use-mono: false

      # Run the Godot project to check for any errors or warnings
      - name: Run Godot 4.3 Project
        run: |
          godot --headless --path "path/to/your/project" --no-window --export-debug "Linux/X11"

      # Optional: Run unit tests, if applicable
      - name: Run Godot Unit Tests
        run: |
          godot --headless --path "path/to/your/project" --no-window --test
